#!/bin/bash 
#
# Creats a symlink from your $JBOSS_HOME/standalone/deployments folder to the
# current folder (which must be the exploded WAR that you would like to
# deploy). Also creates the necessary ".dodeploy" marker file in the JBoss
# deployments folder.
#
# The exploded WAR will be created automatically by maven in the "target" folder
# of your module. We use exploded WARs instead of compressed WARs to facilitate
# hot-deploying resources as they are changed.
#
# To use:
#
#  1. `cd` into the exploded war that you would like deployed.
#
#  2. Run `ldeploy` (creates deployment symlink)
#
#  3. Start Wildfly


# you should be in the target directory of your project
two_dirs_up=$(basename $(dirname $(pwd)))
if [ $two_dirs_up != "target" ]; then
    echo "You should execute this script from the exploded WAR of your project."
    exit 1
fi

full_path=$(pwd)
war_name=$(basename $(pwd))

cd $JBOSS_HOME/standalone/deployments/
echo "creating symlink $war_name.war"
echo "  from $(pwd)"
echo "  to $full_path"

ln -s $full_path "$war_name.war"
touch "$war_name.war.dodeploy"
