#!/bin/bash 
#
# Deploy a current project to a local server, or clean the deployments in a
# local server.
#
# To deploy a procject, ldeploy creats a symlink from the server's deployments
# folder to the current folder (which must be the exploded WAR that you would
# like to deploy). Also creates the necessary ".dodeploy" marker file for JBoss.
#
# Usage:
# ldeploy [jboss|tomcat] [clean]
#
# Examples:
# 
# ldeploy jboss clean
#
#     Removes all deployments in your local JBoss
#
# ldeploy clean
#
#     Same as `ldeploy jboss clean`. ldeploy defaults to JBoss.
#
# cd <exploded_war_path>
# ldeploy jboss
# 
#     Deploys the current exploded war to JBoss



case $1 in

    jboss)
	server="jboss"
	shift
    ;;

    tomcat)
	server="tomcat"
	shift
    ;;

    *)
	echo "defaulting server to JBoss"
        server="jboss"
    ;;

esac

# set necessary variables depending on server
if [ $server == "jboss" ]; then
    DEPLOYMENT_FOLDER=$JBOSS_HOME/standalone/deployments
    war_name=$(basename $(pwd)).war
elif [ $server == "tomcat" ]; then
    DEPLOYMENT_FOLDER=$CATALINA_HOME/webapps
    war_name=$(basename $(pwd))
fi

case $1 in 

    # remove everything in the server's deployment folder
    clean)
	echo "server is $server"
	
	cd $DEPLOYMENT_FOLDER

	# to remove JBoss deployment, we need to remove any '.war' file
	# (symlinks and .war.dodeploy files)
	if [ $server == "jboss" ]; then
	    echo "removing deployed apps in $DEPLOYMENT_FOLDER"
	    rm *\.war*
	fi

	# to remove Tomcat deployment, we can remove any symlinks in the
	# 'webapps' folder
	if [ $server == "tomcat" ]; then
	    echo "removing deployed apps in $DEPLOYMENT_FOLDER"
	    find . -maxdepth 1 -type l -exec rm -rf {} +
	fi
    ;;

    # deploy the current project to the server
    *)
	echo "server is $server"

	# you should be in the target directory of your project
	two_dirs_up=$(basename $(dirname $(pwd)))
	if [ $two_dirs_up != "target" ]; then
	    echo "You should execute this script from the exploded WAR of your project."
	    exit 1
	fi

	exploded_war_path=$(pwd)
	cd $DEPLOYMENT_FOLDER

	echo "creating symlink $war_name"
	echo "  from $(pwd)"
	echo "  to $exploded_war_path"
	
	ln -s $exploded_war_path "$war_name"

	if [ $server == "jboss" ]; then
	    touch "$war_name.war.dodeploy"
	fi
    ;;

esac
