#!/bin/bash 
#
# Deploy a current project to a local server, or clean the deployments in a
# local server.
#
# To deploy a procject, ldeploy creats a symlink from the server's deployments
# folder to the current folder (which must be the exploded WAR that you would
# like to deploy). Also creates the necessary ".dodeploy" marker file for JBoss.
#
# Usage:
# ldeploy [jboss|tomcat] [clean]
#
# Examples:
# 
# ldeploy jboss clean
#
#     Removes all deployments in your local JBoss
#
# ldeploy clean
#
#     Same as `ldeploy jboss clean`. ldeploy defaults to JBoss.
#
# cd <exploded_war_path>
# ldeploy jboss
# 
#     Deploys the current exploded war to JBoss

case $1 in

    jboss)
	server="jboss"
	DEPLOYMENT_FOLDER=$JBOSS_HOME/standalone/deployments
	shift
    ;;

    tomcat)
	#todo
	server="tomcat"
	DEPLOYMENT_FOLDER=$CATALINA_HOME/webapps
	shift
    ;;

    *)
	echo "defaulting server to JBoss"
        server="jboss"
	DEPLOYMENT_FOLDER=$JBOSS_HOME/standalone/deployments
    ;;

esac

case $1 in 

    # remove everything in the server's deployment folder
    clean)
	echo "server is $server"
	
	cd $DEPLOYMENT_FOLDER

	# to remove JBoss deployment, we need to remove any '.war' file
	# (symlinks, WARs, and .war.dodeploy files)
	if [ $server == "jboss" ]; then
	    echo "removing deployed apps in $DEPLOYMENT_FOLDER"
	    rm *\.war*
	fi

	# to remove Tomcat deployment, we need to remove any directories in the
	# 'webapps' folder that aren't titeld [ROOT | docs | manager |
	# host-manager | examples]
	if [ $server == "tomcat" ]; then
	    echo "removing deployed apps in $DEPLOYMENT_FOLDER"
	    find . -maxdepth 1 ! -name ROOT -a ! -name docs -a ! -name manager -a ! -name host-manager -a ! -name examples -a ! -name . -type d -exec rm -rf {} +
	fi
    ;;

    # deploy the current project to the server
    *)
	echo "server is $server"

	# you should be in the target directory of your project
	two_dirs_up=$(basename $(dirname $(pwd)))
	if [ $two_dirs_up != "target" ]; then
	    echo "You should execute this script from the exploded WAR of your project."
	    exit 1
	fi
	
	full_path=$(pwd)
	war_name=$(basename $(pwd))

	cd $DEPLOYMENT_FOLDER

	echo "creating symlink $war_name.war"
	echo "  from $(pwd)"
	echo "  to $full_path"
	
	ln -s $full_path "$war_name.war"

	if [ $server == "jboss" ]; then
	    touch "$war_name.war.dodeploy"
	fi
    ;;

esac
