#!/bin/bash
#
# Wrapper for 'mvn' that colorizes output and creates a desktop notification
# upon completion.

# Formatting constants
BOLD=`tput bold`
UNDERLINE_ON=`tput smul`
UNDERLINE_OFF=`tput rmul`
TEXT_BLACK=`tput setaf 0`
TEXT_RED=`tput setaf 1`
TEXT_GREEN=`tput setaf 2`
TEXT_YELLOW=`tput setaf 3`
TEXT_BLUE=`tput setaf 4`
TEXT_MAGENTA=`tput setaf 5`
TEXT_CYAN=`tput setaf 6`
TEXT_WHITE=`tput setaf 7`
BACKGROUND_BLACK=`tput setab 0`
BACKGROUND_RED=`tput setab 1`
BACKGROUND_GREEN=`tput setab 2`
BACKGROUND_YELLOW=`tput setab 3`
BACKGROUND_BLUE=`tput setab 4`
BACKGROUND_MAGENTA=`tput setab 5`
BACKGROUND_CYAN=`tput setab 6`
BACKGROUND_WHITE=`tput setab 7`
RESET_FORMATTING=`tput sgr0`
 
# Wrapper function for Maven's mvn command. Use sed to replace certain words
# with colorized versions of themselves.
mvn-color() {
  # if --unbuffered isn't used, output is very choppy (refreshes every second or
  # two). TODO: make 2-digit numbers in test output colorized correctly.
  mvn $@ | sed --unbuffered \
      -e "s/^\(\[INFO\] --- \)\(.*-plugin\)/\1${TEXT_BLUE}\2${RESET_FORMATTING}/" \
      -e "s/\( WARNING \)/${TEXT_YELLOW}\1${RESET_FORMATTING}/" \
      -e "s/\( SUCCESS \)/${TEXT_GREEN}\1${RESET_FORMATTING}/" \
      -e "s/\( SKIPPED\)/${TEXT_YELLOW}\1${RESET_FORMATTING}/" \
      -e "s/\( FAILURE \)/${TEXT_RED}\1${RESET_FORMATTING}/" \
      -e "s/\(\[WARN\].*\)/${TEXT_YELLOW}\1${RESET_FORMATTING}/" \
      -e "s/\(\[ERROR\]\)/${TEXT_RED}\1${RESET_FORMATTING}/" \
      -e "s/\(Tests run: [1-9]\)/${TEXT_GREEN}\1${RESET_FORMATTING}/" \
      -e "s/\(Failures: [1-9]\)/${TEXT_RED}\1${RESET_FORMATTING}/" \
      -e "s/\(Errors: [1-9]\)/${TEXT_RED}\1${RESET_FORMATTING}/" \
      -e "s/\(Skipped: [1-9]\)/${TEXT_YELLOW}\1${RESET_FORMATTING}/"

  # the 'last' command run was sed, but we can still get the return code of mvn
  # using the bulit-in bash $PIPESTATUS variable
  MVN_RETCODE=${PIPESTATUS[0]}
  echo "maven retcode is" $MVN_RETCODE
 
  # Make sure formatting is reset
  echo -ne ${RESET_FORMATTING}
}

# choose icons for desktop notifications
success_icon=/usr/share/icons/gnome/32x32/emotes/face-cool.png
failure_icon=/usr/share/icons/gnome/32x32/emotes/face-angry.png

# execute our maven colorizer, and take some action based on the return code
mvn-color "$@"

# a return code of 0 indicates success. A nonzero return code indicates failure.
if [[ $MVN_RETCODE != 0 ]]; then
    notify-send -i $failure_icon "'$(basename $0)' got fucked up"
else
    notify-send -i $success_icon "'$(basename $0)' finished!"
fi

exit $RETCODE
